### PR TITLE
Specs and docs contrasting cmp/2 vs compare/2

### LINKED ISSUE #30: cmp claims it can return `:qNan`, but no case returns it
Both the `@doc` and `@spec` claim `cmp/2` can return `:qNan`, but there is no clause that returns `:qNan`. 
```
  @doc """
  Compares two numbers numerically. If the first number is greater than the second
  `:gt` is returned, if less than `:lt` is returned, if both numbers are equal
  `:eq` is returned. Otherwise, if any number is a `NaN`, NaN is returned.
  """
  @spec cmp(t, t) :: :lt | :eq | :gt | :qNaN
  def cmp(num1, num2) do
    case compare(num1, num2) do
      %Decimal{coef: 1, sign: -1} -> :lt
      %Decimal{coef: 0} -> :eq
      %Decimal{coef: 1, sign: 1} -> :gt
    end
  end
```
--- https://github.com/ericmj/decimal/blob/master/lib/decimal.ex#L289-L301

Looking at `compare/2`:

```
  @doc """
  Compares two numbers numerically. If the first number is greater than the second
  `#Decimal<1>` is returned, if less than `Decimal<-1>` is returned. Otherwise,
  if both numbers are equal `Decimal<0>` is returned.
  """
  @spec compare(t, t) :: t
  def compare(%Decimal{coef: coef1} = num1, %Decimal{coef: coef2} = num2) do
    cond do
      coef1 == :qNaN ->
        num1
      coef2 == :qNaN ->
        num2
      true ->
        case sub(num1, num2) do
          %Decimal{coef: 0} -> %Decimal{sign: 1, coef: 0}
          %Decimal{sign: sign} -> %Decimal{sign: sign, coef: 1}
        end
    end
  end
```

The `:qNan` involved are for the `coef`.  Since if either number has `coef` of `:qNan`, that `Decimal` is returned, and the clauses in `cmp` never match on a `coef` of `:qNan`, if such a `Decimal` were involved in a `cmp`, an exception would be raise:

```
iex> nan = Decimal.new("nan")
#Decimal<NaN>
iex> Decimal.compare(nan, nan)
#Decimal<NaN>
iex> Decimal.cmp(nan, nan)
** (CaseClauseError) no case clause matching: #Decimal<NaN>
    (decimal) lib/decimal.ex:296: Decimal.cmp/2
```

### PR DESCRIPTION
**Pull request by KronicDeth**
Fixes #30

# Changelog
## Enhancements
* Document `compare/2` handles quite NaNs
* Add pointer from `cmp/2` to `compare/2` for users that are looking for comparison of potential quiet NaNs.

## Bug Fixes
* Remove `:qNaN` from `cmp/2` `@spec`, as it doesn't return that value and doesn't handle NaNs at all, which is now shown in the docs.

### CODE REVIEW

File: lib/decimal.ex [hunk 1]
```diff
@@ -269,7 +269,8 @@ defmodule Decimal do
   @doc """
   Compares two numbers numerically. If the first number is greater than the second
   `#Decimal<1>` is returned, if less than `Decimal<-1>` is returned. Otherwise,
-  if both numbers are equal `Decimal<0>` is returned.
+  if both numbers are equal `Decimal<0>` is returned.  If either number is a quite
```
Comment (ericmj) [inline lib/decimal.ex]: s/quite/quiet

File: lib/decimal.ex [hunk 2]
```diff
@@ -289,9 +290,12 @@ defmodule Decimal do
   @doc """
   Compares two numbers numerically. If the first number is greater than the second
   `:gt` is returned, if less than `:lt` is returned, if both numbers are equal
-  `:eq` is returned. Otherwise, if any number is a `NaN`, NaN is returned.
+  `:eq` is returned.
+
+  Neither number can be a `NaN`.  If you need to handle quiet NaNs, use `compare/2`, but it returns `t` instead of
+  `:lt | :eq | :gt`.
```
Comment (ericmj) [inline lib/decimal.ex]: I think we should remove everything after the comma. The behavior of `compare/2` should be clear when reading the docs for it.

File: lib/decimal.ex (hunk 1 above)
Comment (KronicDeth) [inline lib/decimal.ex]: Fixed in the rebase (81b35b3)

File: lib/decimal.ex (hunk 2 above)
Comment (KronicDeth) [inline lib/decimal.ex]: Fixed in the rebase (81b35b3)

**Comment by ericmj** [comment]
Perfect, thank you!
